<div class="loading">
  <div class="loadingio-spinner-dual-ring-nkhucm6h71h">
    <div class="ldio-vbdt8ul1omn">
      <div />
      <div><div /></div>
    </div>
  </div>
</div>

<style>
  .loading {
    display: flex;
    justify-content: center;
    align-items: center;
    margin: 2rem;
  }

  @keyframes ldio-vbdt8ul1omn {
    0% {
      transform: rotate(0);
    }
    100% {
      transform: rotate(360deg);
    }
  }
  .ldio-vbdt8ul1omn div {
    box-sizing: border-box !important;
  }
  .ldio-vbdt8ul1omn > div {
    position: absolute;
    width: 144px;
    height: 144px;
    top: 28px;
    left: 28px;
    border-radius: 50%;
    border: 16px solid #000;
    border-color: #fe718d transparent #fe718d transparent;
    animation: ldio-vbdt8ul1omn 1s linear infinite;
  }
  .ldio-vbdt8ul1omn > div:nth-child(2) {
    border-color: transparent;
  }
  .ldio-vbdt8ul1omn > div:nth-child(2) div {
    position: absolute;
    width: 100%;
    height: 100%;
    transform: rotate(45deg);
  }
  .ldio-vbdt8ul1omn > div:nth-child(2) div:before,
  .ldio-vbdt8ul1omn > div:nth-child(2) div:after {
    content: "";
    display: block;
    position: absolute;
    width: 16px;
    height: 16px;
    top: -16px;
    left: 48px;
    background: #fe718d;
    border-radius: 50%;
    box-shadow: 0 128px 0 0 #fe718d;
  }
  .ldio-vbdt8ul1omn > div:nth-child(2) div:after {
    left: -16px;
    top: 48px;
    box-shadow: 128px 0 0 0 #fe718d;
  }
  .loadingio-spinner-dual-ring-nkhucm6h71h {
    width: 200px;
    height: 200px;
    display: inline-block;
    overflow: hidden;
    background: #ffffff;
  }
  .ldio-vbdt8ul1omn {
    width: 100%;
    height: 100%;
    position: relative;
    transform: translateZ(0) scale(1);
    backface-visibility: hidden;
    transform-origin: 0 0;
  }
  .ldio-vbdt8ul1omn div {
    box-sizing: content-box;
  }
  /* generated by https://loading.io/ */
</style>
